- name: Do tasks for a normal PC
  hosts: localhost
  connection: local
  become: true
  tags: default

  pre_tasks:
    - name: Ansible-pull warning notice
      debug:
        msg: |
          =========================================
          IMPORTANT:
          The warning "Could not match supplied host pattern"
          is expected when using ansible-pull.
          You can safely ignore it.
          =========================================

  roles:
    - role: default

- name: Do tasks for a laptop
  hosts: localhost
  connection: local
  become: true
  tags: laptop

  pre_tasks:
    - name: Ansible-pull warning notice
      debug:
        msg: |
          =========================================
          IMPORTANT:
          The warning "Could not match supplied host pattern"
          is expected when using ansible-pull.
          You can safely ignore it.
          =========================================

  roles:
    - role: laptop

- name: Do tasks for a kali vm
  hosts: localhost
  connection: local
  become: true
  tags: kali

  pre_tasks:
    - name: Ansible-pull warning notice
      debug:
        msg: |
          =========================================
          IMPORTANT:
          The warning "Could not match supplied host pattern"
          is expected when using ansible-pull.
          You can safely ignore it.
          =========================================

  roles:
    - role: kali
