- name: Do tasks for a normal PC
  hosts: localhost
  connection: local
  become: true
  tags: default
  roles:
    - role: default

- name: Do tasks for a laptop
  hosts: localhost
  connection: local
  become: true
  tags: laptop
  roles:
  - role: laptop
