- name: Copy apt sources list file
  ansible.builtin.copy:
    src: files/sources.list
    dest: "/etc/apt/sources.list"
    owner: "root"
    group: "root"
    mode: "644"
    backup: true

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
