- name: Copy bashrc configuration file
  ansible.builtin.copy:
    src: files/.bashrc
    dest: "/home/{{ superuser }}/.bashrc"
    owner: "{{ superuser }}"
    group: "{{ superuser }}"
    mode: "644"
    backup: true

- name: Copy bin configuration files
  ansible.builtin.copy:
    src: files/bin
    dest: "/home/{{ superuser }}/.local/bin"
    owner: "{{ superuser }}"
    group: "{{ superuser }}"
    mode: "700"
    backup: true

- name: Copy btop configuration file
  ansible.builtin.copy:
    src: files/btop
    dest: "/home/{{ superuser }}/.config/btop"
    owner: "{{ superuser }}"
    group: "{{ superuser }}"
    mode: "755"
    backup: true

- name: Copy VSCode configuration file
  ansible.builtin.copy:
    src: files/Code
    dest: "/home/{{ superuser }}/.config/Code"
    owner: "{{ superuser }}"
    group: "{{ superuser }}"
    mode: "700"
    backup: true

- name: Copy neovim configuration file
  ansible.builtin.copy:
    src: files/nvim
    dest: "/home/{{ superuser }}/.config/nvim"
    owner: "{{ superuser }}"
    group: "{{ superuser }}"
    mode: "755"
    backup: true

- name: Copy configuration file
  ansible.builtin.copy:
    src: files/safeeyes
    dest: "/home/{{ superuser }}/.config/safeeyes"
    owner: "{{ superuser }}"
    group: "{{ superuser }}"
    mode: "755"
    backup: true