- name: Install Docker
  ansible.builtin.apt:
    name: "{{ docker }}"

- name: Add non-root user to docker group
  ansible.builtin.user:
    name: "{{ superuser }}"
    groups: "docker"
    append: yes

- name: Restart docker in systemd
  ansible.builtin.systemd_service:
    name: docker
    state: reloaded
