- name: Enable non-free repositories
  include_tasks: repo.yml

- name: Disable Root
  include_tasks: root_disable.yml

- name: Configure ram usage
  include_tasks: ram.yml

- name: Update and configure packages
  include_tasks: packages.yml

- name: Install and enable Docker
  include_tasks: docker.yml

- name: Install and enable Firewalld
  include_tasks: firewall.yml

- name: Install and enable QEMU-KVM
  include_tasks:  qemu.yml

- name: Install and enable ClamAV
  include_tasks: clam.yml

- name: Install and enable Flatpak
  include_tasks: flatpak.yml

- name: Configure grub
  include_tasks: grub.yml
