- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true

- name: Perform dist-upgrade
  ansible.builtin.apt:
    upgrade: dist
    dpkg_options: "force-confold,force-confdef"

- name: Install Packages
  ansible.builtin.apt:
    name: "{{ package_install }}"
    state: absent

- name: Remove Packages
  ansible.builtin.apt:
    name: "{{ package_remove }}"

- name: Enable and run unattended-upgrades in systemd
  ansible.builtin.systemd_service:
    name: unattended-upgrades.service
    state: started
    enabled: true