- name: Install Zram-tools
  ansible.builtin.apt:
    name: zram-tools

- name: Change swappiness value to 10
  ansible.builtin.lineinfile:
    path: /etc/sysctl.conf
    line: vm.swappiness = 10
    create: yes