- name: Append Debian repository with non-free sources
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list
    regexp: "deb http://deb.debian.org/debian/ trixie main non-free-firmware"
    line: "deb http://deb.debian.org/debian/ trixie main non-free-firmware contrib non-free"

- name: Append Debian source repository with non-free sources
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list
    regexp: "deb-src http://deb.debian.org/debian/ trixie main non-free-firmware"
    line: "deb-src http://deb.debian.org/debian/ trixie main non-free-firmware contrib non-free"

- name: Append Debian security repository with non-free sources
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list
    regexp: "deb http://security.debian.org/debian-security trixie-security main non-free-firmware"
    line: "deb http://security.debian.org/debian-security trixie-security main non-free-firmware contrib non-free"

- name: Append Debian security source repository with non-free sources
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list
    regexp: "deb-src http://security.debian.org/debian-security trixie-security main non-free-firmware"
    line: "deb-src http://security.debian.org/debian-security trixie-security main non-free-firmware contrib non-free"

- name: Append Debian trixie repository with non-free sources
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list
    regexp: "deb http://deb.debian.org/debian/ trixie-updates main non-free-firmware"
    line: "deb http://deb.debian.org/debian/ trixie-updates main non-free-firmware contrib non-free"

- name: Append Debian trixie repository with non-free sources
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list
    regexp: "deb-src http://deb.debian.org/debian/ trixie-updates main non-free-firmware"
    line: "deb-src http://deb.debian.org/debian/ trixie-updates main non-free-firmware contrib non-free"
