clamav:
  - clamav
  - clamtk

docker:
  - docker
  - docker-bash-completion
  - docker-bench-security
  - docker-buildx
  - docker-compose
  - docker-rootless-extras
  - patterns-containers-runtime_docker
  - container_runtime_docker

firewall:
  - firewalld
  - firewalld-bash-completion

qemu:
  - canokey-qemu
  - ipxe-qemu
  - libvirt-daemon-driver-qemu
  - libvirt-daemon-qemu
  - qemu
  - qemu-audio-spice
  - qemu-block-curl
  - qemu-block-nfs
  - qemu-block-rbd
  - qemu-chardev-spice
  - qemu-hw-display-qxl
  - qemu-hw-display-virtio-gpu
  - qemu-hw-display-virtio-gpu-pci
  - qemu-hw-display-virtio-vga
  - qemu-hw-usb-host
  - qemu-hw-usb-redirect
  - qemu-hw-usb-smartcard
  - qemu-img
  - qemu-ksm
  - qemu-linux-user
  - qemu-microvm
  - qemu-ovmf-x86_64
  - qemu-pr-helper
  - qemu-seabios
  - qemu-tools
  - qemu-ui-curses
  - qemu-ui-gtk
  - qemu-ui-opengl
  - qemu-ui-spice-app
  - qemu-ui-spice-core
  - qemu-vgabios
  - qemu-vmsr-helper
  - qemu-x86
  - system-user-qemu
  - libvirt-client
  - libvirt-client-qemu
  - libvirt-daemon
  - libvirt-daemon-common
  - libvirt-daemon-config-network
  - libvirt-daemon-driver-network
  - libvirt-daemon-driver-nodedev
  - libvirt-daemon-driver-qemu
  - libvirt-daemon-driver-secret
  - libvirt-daemon-driver-storage
  - libvirt-daemon-driver-storage-core
  - libvirt-daemon-driver-storage-disk
  - libvirt-daemon-driver-storage-iscsi
  - libvirt-daemon-driver-storage-iscsi-direct
  - libvirt-daemon-driver-storage-logical
  - libvirt-daemon-driver-storage-mpath
  - libvirt-daemon-driver-storage-rbd
  - libvirt-daemon-driver-storage-scsi
  - libvirt-daemon-lock
  - libvirt-daemon-log
  - libvirt-daemon-plugin-lockd
  - libvirt-daemon-qemu
  - libvirt-glib-1_0-0
  - libvirt-libs
  - python313-libvirt-python
  - system-group-libvirt
  - typelib-1_0-LibvirtGLib-1_0
  - virt-install
  - virt-manager
  - virt-manager-common
  - virt-v2v
  - virt-v2v-bash-completion
  - virt-viewer
  - virt-what
  - virtiofsd
